// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCYnCE8hwCp7RDu04SOra_a7nEwpU4rEjw',
    appId: '1:890336873900:web:985c4cb676bb486f9f7e09',
    messagingSenderId: '890336873900',
    projectId: 'draw-33538',
    authDomain: 'draw-33538.firebaseapp.com',
    databaseURL: 'https://draw-33538-default-rtdb.firebaseio.com',
    storageBucket: 'draw-33538.firebasestorage.app',
    measurementId: 'G-59PTY8Z9XG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7zbAgqW_DneJTXXp4Z5NkAF2GrirycOQ',
    appId: '1:890336873900:android:b45a18a5af842a629f7e09',
    messagingSenderId: '890336873900',
    projectId: 'draw-33538',
    databaseURL: 'https://draw-33538-default-rtdb.firebaseio.com',
    storageBucket: 'draw-33538.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC__btwkhzEFpYHSAMr5YRJQFOh5tEOeVQ',
    appId: '1:890336873900:ios:ebf576817966bd449f7e09',
    messagingSenderId: '890336873900',
    projectId: 'draw-33538',
    databaseURL: 'https://draw-33538-default-rtdb.firebaseio.com',
    storageBucket: 'draw-33538.firebasestorage.app',
    iosBundleId: 'com.nurehub.spellit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC__btwkhzEFpYHSAMr5YRJQFOh5tEOeVQ',
    appId: '1:890336873900:ios:5cbfdbf8eec98b379f7e09',
    messagingSenderId: '890336873900',
    projectId: 'draw-33538',
    databaseURL: 'https://draw-33538-default-rtdb.firebaseio.com',
    storageBucket: 'draw-33538.firebasestorage.app',
    iosBundleId: 'com.example.spellit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCYnCE8hwCp7RDu04SOra_a7nEwpU4rEjw',
    appId: '1:890336873900:web:1c5a5859b57001539f7e09',
    messagingSenderId: '890336873900',
    projectId: 'draw-33538',
    authDomain: 'draw-33538.firebaseapp.com',
    databaseURL: 'https://draw-33538-default-rtdb.firebaseio.com',
    storageBucket: 'draw-33538.firebasestorage.app',
    measurementId: 'G-GTX6BLZVEE',
  );

}