// import 'package:cloud_firestore/cloud_firestore.dart';
// import 'package:flutter_riverpod/flutter_riverpod.dart';
// import '../../models/chat_model.dart';

// final chatServiceProvider = Provider((ref) => ChatService());

// class ChatService {
//   final FirebaseFirestore _firestore = FirebaseFirestore.instance;

//   // Stream global messages, ordered by timestamp descending, limited to 50
//   Stream<List<ChatMessage>> getGlobalChatStream() {
//     return _firestore
//         .collection('global_chats')
//         .orderBy('timestamp', descending: true)
//         .limit(50)
//         .snapshots()
//         .map((snapshot) => snapshot.docs
//             .map((doc) => ChatMessage.fromFirestore(doc))
//             .toList());
//   }

//   // Send a message to global chat
//   Future<void> sendGlobalMessage(String senderId, String senderName, String text) async {
//     if (text.trim().isEmpty) return;

//     final msg = ChatMessage(
//       id: '', // Will be generated by firestore
//       senderId: senderId,
//       senderName: senderName,
//       text: text.trim(),
//       timestamp: DateTime.now(),
//     );

//     await _firestore.collection('global_chats').add(msg.toFirestore());
//   }

//   // Get private chat stream between two users
//   Stream<List<ChatMessage>> getPrivateChatStream(String currentUserId, String otherUserId) {
//     final chatId = _getPrivateChatId(currentUserId, otherUserId);
//     return _firestore
//         .collection('private_chats')
//         .doc(chatId)
//         .collection('messages')
//         .orderBy('timestamp', descending: true)
//         .limit(50)
//         .snapshots()
//         .map((snapshot) => snapshot.docs
//             .map((doc) => ChatMessage.fromFirestore(doc))
//             .toList());
//   }

//   Future<void> sendPrivateMessage(
//     String currentUserId,
//     String currentUserName,
//     String otherUserId,
//     String text,
//   ) async {
//     if (text.trim().isEmpty) return;

//     final chatId = _getPrivateChatId(currentUserId, otherUserId);
//     final chatRef = _firestore.collection('private_chats').doc(chatId);
//     final existing = (await chatRef.get()).data() ?? {};
//     final participants = List<String>.from(existing['participants'] ?? [currentUserId, otherUserId]);
//     final uidA = participants[0];
//     final uidB = participants.length > 1 ? participants[1] : otherUserId;

//     final currentUserNameSafe = currentUserName.isEmpty ? 'Player' : currentUserName;
//     final nameA = existing['name_$uidA'] ?? (uidA == currentUserId ? currentUserNameSafe : await _resolveName(uidA));
//     final nameB = existing['name_$uidB'] ?? (uidB == currentUserId ? currentUserNameSafe : await _resolveName(uidB));

//     final msg = ChatMessage(
//       id: '',
//       senderId: currentUserId,
//       senderName: currentUserNameSafe,
//       text: text.trim(),
//       timestamp: DateTime.now(),
//     );

//     await chatRef.collection('messages').add(msg.toFirestore());

//     await chatRef.set({
//       'participants': [uidA, uidB],
//       'lastMessage': text.trim(),
//       'lastMessageTime': FieldValue.serverTimestamp(),
//       'name_$uidA': nameA,
//       'name_$uidB': nameB,
//     }, SetOptions(merge: true));
//   }

//   Future<String?> _resolveName(String uid) async {
//     try {
//       final doc = await _firestore.collection('users').doc(uid).get();
//       if (doc.exists) {
//         final name = doc.get('displayName') as String?;
//         if (name != null && name.isNotEmpty) return name;
//       }
//     } catch (_) {}
//     return null;
//   }

//   // Helper to generate a consistent chat ID between two users
//   String _getPrivateChatId(String uid1, String uid2) {
//     final ids = [uid1, uid2];
//     ids.sort();
//     return '${ids[0]}_${ids[1]}';
//   }

//   // Get a stream of recent private chats for a user
//   Stream<List<Map<String, dynamic>>> getRecentPrivateChats(String userId) {
//     return _firestore
//         .collection('private_chats')
//         .where('participants', arrayContains: userId)
//         .limit(50)
//         .snapshots()
//         .map((snapshot) {
//           final result = <Map<String, dynamic>>[];
//           for (final doc in snapshot.docs) {
//             final data = doc.data();
//             final participants = List<String>.from(data['participants'] ?? []);
//             final otherUserId = participants.firstWhere(
//               (id) => id != userId,
//               orElse: () => doc.id,
//             );

//             result.add({
//               'id': doc.id,
//               'otherUserId': otherUserId,
//               'lastMessage': data['lastMessage'] ?? '',
//               'lastMessageTime': (data['lastMessageTime'] is Timestamp)
//                   ? (data['lastMessageTime'] as Timestamp).toDate()
//                   : DateTime.now(),
//               'participants': participants,
//             });
//           }
//           result.sort((a, b) {
//             final ta = a['lastMessageTime'] as DateTime;
//             final tb = b['lastMessageTime'] as DateTime;
//             return tb.compareTo(ta);
//           });
//           return result;
//         });
//   }
// }
